- server/src/airtable-interface.js
- server/src/index.js
- website/public/assets/initial.css
- website/public/index.html
- website/src/apps/GlobalApp.vue
- website/src/apps/MinisiteWrapperApp.vue
- website/src/apps/WebsiteApp.vue
- website/src/components/website/WebsiteNav.vue
- website/src/main.js
- website/src/router/default.js
- website/src/router/event.js
- website/src/router/index.js
- website/src/router/shared-routes.js
- website/src/thing-store.js
- website/src/utils/fetch.js
- website/src/views/Event.vue
- website/src/views/LoadingPage.vue
- website/src/views/NotFoundPage.vue
- website/src/views/lists/Players.vue
- website/src/views/lists/Teams.vue
- website/vue.config.js
As in #13:
SLMN.GG allows some remapping and style changes for some events and teams, for example:
slmn.gg/event/-bpl-id- -> bpl.slmn.gg
slmn.gg/event/-bpl-id-/teams -> bpl.slmn.gg/teams
Expected functionality:
There is a discussion on what should still be accessible from a minisite page. Where should a minsite end? Should the minisite open other events in a new tab on slmn.gg at some point?
> Add subdomain support

- website/src/components/website/DetailedMatchStat.vue
- website/src/views/DetailedMatch.vue
> Make staff names on the detailed match page clickable like the regular match page

- website/src/components/broadcast/roots/SyncerOverlay.vue
> Make Syncer be at the top of page instead of centered

- website/src/views/sub-views/PlayerMatches.vue
- Adds a bar above matches showing the number of each type of work done on a match
- Links that bring you further down the page to the section named
- Fix for [Issue #73](https://github.com/slmnio/slmngg-sfc/issues/73)
https://user-images.githubusercontent.com/87488710/148659727-66261c38-e01f-4f3c-89bd-292e1c841a97.mp4
> Add count for matches worked on to player matches page

- server/src/index.js
- website/src/components/broadcast/roots/TallyTransmitter.vue
- website/src/components/broadcast/roots/TallyViewer.vue
- website/src/router/broadcast.js
- This adds a tally light system based on the OBS browser bindings
- Inside OBS a browser source with the url `/client/<clientname>/tally-transmitter` is added to scene of the corresponding observer's feed
- A viewer of the tally light visits `/client/<clientname>/tally-viewer`
- When the scene changes the OBS browser source notifies subscribed clients about the change
https://user-images.githubusercontent.com/23165606/148659135-db09be25-c833-4186-b501-d8d5ec92adcf.mp4
> Add tally lights overlay powered by obs scene changes

- website/src/components/broadcast/PlayerHero.vue
- website/src/components/broadcast/PlayerHistory.vue
- website/src/components/broadcast/auction/PlayerTeamDisplay.vue
- website/src/router/broadcast.js
- website/src/views/lists/NewEventDisplay.vue
Add a scene that displays a player's career history, potentially expandable to display things such as favorite hero or career win percentage
> Add Player History Scene

- website/src/components/website/LinkedPlayers.vue
- website/src/components/website/match/DetailedMatchStat.vue
- website/src/views/DetailedMatch.vue
I added the tally links of all observers for the current match to the detailed match page. I also refactored parts of the stat component.
> Add tally light links to detailed match page

- website/src/components/website/LinkedPlayers.vue
This just uses dev.slmn.gg as a fallback when on minisites
> Fix bug when tally lights links were used on minisites

- server/.eslintrc.json
- server/src/meta.js
While working on adding some more meta information I found the if statements that were checking for things like images to be annoying. A lot of them can be removed by using optional chaining and clearing undefined values from the data object before merging it with the default data.
Going from this: 
```js
if (theme) {
data.color = theme.color_theme;
}
if (thing.thumbnail) {
data.image = aImg(thing.thumbnail, "w-1000");
data.card_type = "summary_large_image";
}
if (!data.image && thing.header) {
data.image = aImg(thing.header, "w-1000");
data.card_type = "summary_large_image";
}
if (!data.image && theme?.default_wordmark) data.image = aImg(theme.default_wordmark);
if (!data.image && theme?.default_logo) data.image = aImg(theme.default_logo);
```
To this:
```js
color: theme?.color_theme, …
```
> Refactor meta code to use more optional chaining and reduce boilerplate

- website/src/components/broadcast/roots/TallyTransmitter.vue
- website/src/components/broadcast/roots/TallyViewer.vue
If the `?num=<n>` parameter is provided to the tally transmitter the selected `/client/<client>` will be used to fetch the current match, get its observers and select the `<n>`'th observer in the list for transmission.
The Tally Viewer will now stay awake in [supported browsers](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API#browser_compatibility) using the [Wake Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API).
> Improvements to Tally Transmitter and Viewer

- server/src/airtable-interface.js
- website/package.json
- website/src/components/broadcast/roots/MusicOverlay.vue
- website/src/router/broadcast.js
- website/yarn.lock
This PR ports the old music player into SLMN.gg.
- Song data is moved into airtable for quick editing
- Lists of songs are connected to airtable which means that changing a client's broadcast will automatically update the music as well
- Songs can be added to track groups, these groups can be given roles (for example caster bg, break), these groups can then be selected using the `group=<group>` URL parameter
> Add a music player

- server/src/action-utils.js
- server/src/routes.js
- website/src/components/website/TwitchAuthScopeSelector.vue
- website/src/router/default.js
> Add twitch scope selector

- server/src/images.js
This is a temporary, basically untested mitigation for issue #149, though I have no idea how it will react to Airtable's new URL expiration. I also expect GIFs to break again, as Airtable's new URL schema doesn't share file extensions anymore.
> add new airtable cdn domain to allowlist

- website/package.json
- website/src/components/website/CopyTextButton.vue
- website/src/main.js
- website/src/views/DetailedMatch.vue
- website/src/views/sub-views/ThingTheme.vue
- website/yarn.lock
> Add component to copy text

- server/src/actions/set-title.js
- server/src/actions/start-commercial.js
- website/src/components/website/dashboard/Commercials.vue
- website/src/utils/dashboard.js
- website/src/views/Dashboard.vue
> Add action to start commercial

- server/src/actions/manage-prediction.js
This should resolve #156 but it's currently untested and not the most elegant.
> Add match-wide preds and make them default

- website/src/components/broadcast/roots/WebsocketTransmitter.vue
- website/src/router/broadcast.js
- I reused and slightly modified the UI from the tally viewer
- I also removed an unused parameter
> Make the tally transmitter more visually appealing

- website/src/components/website/LoggedInUser.vue
- website/src/components/website/dashboard/TokenModal.vue
- website/src/views/Dashboard.vue
Add a way to copy the token to the dashboard following #173
> Reimplement the copy token ui 

- server/src/discord/commands/prod/detailed.js
Now the first active broadcast is used if there the current channel is not associated with an active broadcast
> Respect client broadcast order for /detailed

- website/src/components/website/WebsiteNav.vue
Sometimes it's useful to run the SLMN.gg frontend with the production data server instead of spinning up a local one.  
However, this can lead to a lot of confusion when you don't notice you're on the wrong data server and your changes aren't showing up. 
This PR adds a banner during local development when the data server is not running on `localhost`/`127.0.0.1`.
> Warn in local development when using non-local data server

- server/src/discord/commands/prod/rtmp.js
- server/src/discord/commands/prod/srt.js
> Allow specifying a user for /srt and /rtmp

- website/src/components/broadcast/roots/BracketOverlay.vue
When a broadcast's bracket key is empty or set to `match` it will resolve bracket based on `liveMatch`. Setting to a specific bracket key will still work as before.
> feat: When no bracket key or bracket key 'match' take match bracket

- website/src/components/website/CreditCreator.vue
- website/src/views/DetailedMatch.vue
Until now there was only a format for YouTube descriptions, I've added new ones for twitter with both a large and inline variant.
This could be expanded with additional formats in the future. I've also hardcoded the emoji for prod roles here, theoretically this could be moved into airtable but idk if it's worth the effort.
> Turn the credits copy button on the match details page into a modal with multiple formats

- website/src/components/broadcast/Squeezable.vue
Looks like the __vnode stuff isn't available on production environments, so fails. Using `this.$el.children` is not the best but it seems like it's the only way.
> Fix squeezable on production environments

- server/src/routes.js
- website/src/utils/games.ts
This will show a box for replay code as Match UUID (pre-setup for stats), adds default pickban settings, and adds the public checkbox in case we want to ever use a !bans type of command like in DFN
> Add rivals settings to games.ts
